trigger:
  branches:
    include:
      - master

pool:
  name: boardgame-projecy

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"
  DOCKER_IMAGE_NAME: "prasannanjaneya/boardgame-project"

stages:
  # -----------------------------
  - stage: Build_and_Test
    displayName: "Maven Build, Test & SonarQube Analysis"
    jobs:
      - job: MavenBuild
        displayName: "Compile, Test & SonarQube"
        steps:
          - task: Maven@4
            displayName: "Maven Build + SonarQube"
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install sonar:sonar'
              options: '-B'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              mavenOptions: '$(MAVEN_OPTS)'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'

  # -----------------------------
  - stage: Dependency_Scan
    displayName: "Trivy Dependency Scan"
    dependsOn: Build_and_Test
    jobs:
      - job: TrivyScan
        displayName: "Scan Source Code Dependencies"
        steps:
          - script: |
              echo "Installing Trivy..."
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
              echo "Running Trivy FS scan on source code..."
              ./trivy fs --format json --output trivy-report-source.json --severity MEDIUM,LOW,UNKNOWN,HIGH,CRITICAL .
            displayName: "Run Trivy Scan on Source Code"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Trivy Source Scan Report"
            inputs:
              PathtoPublish: 'trivy-report-source.json'
              ArtifactName: 'TrivySourceReport'
              publishLocation: 'Container'

  # -----------------------------
  - stage: Build_and_Push_Docker_Image
    displayName: "Build and Push Docker Image"
    dependsOn: Dependency_Scan
    jobs:
      - job: DockerBuildPush
        displayName: "Build & Push Docker Image"
        steps:
          - task: Docker@2
            displayName: "Build and Push Docker Image"
            inputs:
              containerRegistry: 'docker-svc'
              repository: '$(DOCKER_IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(Build.BuildId)'

  # -----------------------------
  - stage: Scan_Docker_Image
    displayName: "Trivy Scan Docker Image"
    dependsOn: Build_and_Push_Docker_Image
    jobs:
      - job: DockerTrivyScan
        displayName: "Scan Docker Image"
        steps:
          - script: |
              echo "Installing Trivy..."
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
              echo "Scanning Docker image $(DOCKER_IMAGE_NAME):$(Build.BuildId)"
              ./trivy image --format json --output trivy-report-image.json --severity MEDIUM,LOW,UNKNOWN,HIGH,CRITICAL $(DOCKER_IMAGE_NAME):$(Build.BuildId)
            displayName: "Run Trivy Docker Image Scan"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Trivy Docker Scan Report"
            inputs:
              PathtoPublish: 'trivy-report-image.json'
              ArtifactName: 'TrivyDockerReport'
              publishLocation: 'Container'
